
id = "http-client"
name = "Http Client"
version = "0.0.4"
schema_version = 1
authors = ["Marc d'Entremont <cramhead@gmail.com>"]
description = "Sends HTTP requests to APIs. Syntax highlights files with a .http extension. Provides code actions so that requests can be executed. Shows the results of the request in a http-responses.http file"
repository = "https://github.com/cramhead/http-client"

